import { INodeProperties } from 'n8n-workflow';

export const loginFields: INodeProperties[] = [
  {
    displayName: 'ℹ️ Como Obter as Chaves da API',
    name: 'apiKeysInfo',
    type: 'notice',
    default: '',
    displayOptions: { show: { operation: ['login'] } },
    options: [],
    description: 'Para obter as chaves X-API-Key e X-API-Secret: 1) Acesse a conta da empresa na Recrutei com um usuário com permissão de acesso, 2) Navegue até "Configurações" > "API", 3) Os tokens da empresa estarão visíveis e disponíveis para utilização',
  },
  {
    displayName: 'Chave Da API (X-API-Key)',
    name: 'xApiKey',
    type: 'string',
    typeOptions: { password: true },
    required: true,
    default: '',
    description: 'Token de identificação da empresa. Para obter: acesse a conta da empresa na Recrutei com um usuário com permissão de acesso em "Configurações" > "API". O token da empresa estará visível e disponível para utilização.',
    displayOptions: { show: { operation: ['login'] } },
  },
  {
    displayName: 'Segredo Da API (X-API-Secret)',
    name: 'xApiSecret',
    type: 'string',
    typeOptions: { password: true },
    required: true,
    default: '',
    description: 'Token secreto de identificação da empresa. Para obter: acesse a conta da empresa na Recrutei com um usuário com permissão de acesso em "Configurações" > "API". O token secreto da empresa estará visível e disponível para utilização.',
    displayOptions: { show: { operation: ['login'] } },
  },
  {
    displayName: 'E-Mail Do Usuário',
    name: 'email',
    type: 'string',
    placeholder: 'name@email.com',
    required: true,
    default: '',
    description: 'Seu endereço de e-mail ou endereço para o qual o token deve ser gerado. Deve ser um e-mail válido cadastrado na conta da empresa.',
    displayOptions: { show: { operation: ['login'] } },
  },
  {
    displayName: 'Senha Do Usuário',
    name: 'password',
    type: 'string',
    typeOptions: { password: true },
    required: true,
    default: '',
    description: 'Senha do endereço de e-mail enviado. Deve ser a senha associada à conta de e-mail fornecida.',
    displayOptions: { show: { operation: ['login'] } },
  },
];
